CREATE TABLE "ADMIN" (
    "ID"            VARCHAR2(50)    NOT NULL,
    "PWD"           VARCHAR2(50)    NULL,
    "NAME"          VARCHAR2(100)   NULL
);

CREATE TABLE "NOTICE" (
    "NOTICE_NO"     NUMBER          NOT NULL,
    "NOTICE_TITLE"  VARCHAR2(100)   NOT NULL,
    "NOTICE_CONTENT"    VARCHAR2(4000)  NOT NULL,
    "NOTICE_DATE"   DATE            NOT NULL
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY ("ID");

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("NOTICE_NO");

commit;
